# Generated by Django 5.2.1 on 2025-05-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asistio',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
